var Fannypack = require('fannypack')
var gulp      = require('gulp')
var $         = Fannypack.$

var render    = require('gulp-nunjucks-render')
var rename    = require('gulp-rename')

var green     = $.Util.colors.green
var blue      = $.Util.colors.blue

module.exports = function(config) {
  return function(glyphs, options) {
    $.Util.log( blue('Generating ' + config.sassDest + '/' + config.sassOutputName) )
    render.nunjucks.configure(config.nunjucks, {watch: false })

    return gulp.src(config.template)
      .pipe(render({
        icons: glyphs.map(function(glyph) {
          $.Util.log( green('+ adding ' + glyph.name + ' glyph') )
          return {
            name: glyph.name,
            code: glyph.unicode[0].charCodeAt(0).toString(16).toUpperCase()
          }
        }),

        fontName: config.options.fontName,
        fontPath: config.fontPath,
        className: config.className,
        comment: '// DO NOT EDIT DIRECTLY!\n  //Generated by fannypack-iconfont\n  //from ' + config.template
      }))
    .on( 'error', $.ErrorHandler)
    .pipe( rename(config.sassOutputName))
    .pipe( gulp.dest(config.sassDest))
  }
}
